@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZTc4Mzk4YWRhMDRlMTZiZTJlMTBiMCIsImlhdCI6MTc2MDA5Mzg3NSwiZXhwIjoxNzY3ODY5ODc1fQ.cQAF8Nqa-QFXGDoedMY4zOBgWzLsVt18VGqyEl57nIw
@host = http://localhost:3000
@uri_prefix = api/v1

GET {{host}}/{{uri_prefix}}/tours?price[lt]=1000
Authorization: Bearer {{token}}

GET {{host}}/{{uri_prefix}}/tours/5c88fa8cf4afda39709c2970
Authorization: Bearer {{token}}

GET {{host}}/{{uri_prefix}}/users
Authorization: Bearer {{token}}

GET {{host}}/{{uri_prefix}}/bookings
Authorization: Bearer {{token}}

GET {{host}}/{{uri_prefix}}/tours/5c88fa8cf4afda39709c2970/reviews
Authorization: Bearer {{token}}

GET {{host}}/{{uri_prefix}}/tours/top-5-cheap
Authorization: Bearer {{token}}

GET {{host}}/{{uri_prefix}}/tours/tour-stats
Authorization: Bearer {{token}}

GET {{host}}/{{uri_prefix}}/tours/monthly-plan/2021
Authorization: Bearer {{token}}

GET {{host}}/{{uri_prefix}}/tours/tours-within/950/center/34.049628,-118.134373/unit/km
Authorization: Bearer {{token}}

GET {{host}}/{{uri_prefix}}/tours/distances/34.049628,-118.134373/unit/km
Authorization: Bearer {{token}}


/////////// DELETE REQUESTS ///////////////////
DELETE {{host}}/{{uri_prefix}}/tours/68e77cf174d3ca42d23dae3f
Authorization: Bearer {{token}}

DELETE {{host}}/{{uri_prefix}}/users/68e78321afe6a66336d48bef
Authorization: Bearer {{token}}

DELETE {{host}}/{{uri_prefix}}/users/deleteMe
Authorization: Bearer {{token2}}


/////////// UPDATE REQUESTS ///////////////////
//"admin@natours.io". "leo@example.com"

POST {{host}}/{{uri_prefix}}/users/login
Content-Type: application/json
{
    "email": "admin@natours.io",
    "password": "test1234"
}

{{
  exports.token = response.parsedBody.token;
}}

PATCH {{host}}/{{uri_prefix}}/tours/5c88fa8cf4afda39709c2955
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="price"

300
--MyBoundary
Content-Disposition: form-data; name="imageCover"; filename="new-tour-1.jpg"
Content-Type: image/jpeg

< ./dev-data/img/new-tour-1.jpg
--MyBoundary
Content-Disposition: form-data; name="images"; filename="new-tour-2.jpg"
Content-Type: image/jpeg

< ./dev-data/img/new-tour-2.jpg
--MyBoundary
Content-Disposition: form-data; name="images"; filename="new-tour-3.jpg"
Content-Type: image/jpeg

< ./dev-data/img/new-tour-3.jpg
--MyBoundary
Content-Disposition: form-data; name="images"; filename="new-tour-4.jpg"
Content-Type: image/jpeg

< ./dev-data/img/new-tour-4.jpg
--MyBoundary--

PATCH {{host}}/{{uri_prefix}}/users/updatePassword
Authorization: Bearer {{token}}
Content-Type: application/json
{
    "passwordCurrent": "my-new-password2",
    "password": "my-new-password",
    "passwordConfirm": "my-new-password"
}

{{
  exports.token = response.parsedBody.token;
}}

POST {{host}}/{{uri_prefix}}/users/forgotPassword
Content-Type: application/json
{
    "email": "luisfilipesobral1@gmail.com"
}

PATCH {{host}}/{{uri_prefix}}/users/updateMe
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="name"

Leo Gill
--MyBoundary
Content-Disposition: form-data; name="photo"; filename="leo.jpg"
Content-Type: image/jpeg

< ./dev-data/img/leo.jpg
--MyBoundary--

PATCH {{host}}/{{uri_prefix}}/users/resetPassword/34d3cca847820098a772f344d9cacdaecd131cfebc3968e384a2f98d56c0e54b
Content-Type: application/json
{
    "password": "my-new-password2",
    "passwordConfirm": "my-new-password2"
}
{{
  exports.token = response.parsedBody.token;
}}


/////////// CREATE REQUESTS ///////////////////
POST {{host}}/{{uri_prefix}}/users/signup
Content-Type: application/json
{
    "name": "luis",
    "email": "luisfilipesobral1@gmail.com",
    "password": "test1234",
    "passwordConfirm": "test1234",
    "role": "admin"
}
{{
  exports.token = response.parsedBody.token;
}}

POST {{host}}/{{uri_prefix}}/tours
Authorization: Bearer {{token}}
Content-Type: application/json
{
    "name": "The Test Tour",
    "duration": 5,
    "maxGroupSize": 25,
    "difficulty": "easy",
    "rating": 4,
    "price": 397,
    "priceDiscount": 300,
    "summary": "Breathtaking hike through the Canadian Banff National Park",
    "description": "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.\nLorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "imageCover": "tour-1-cover.jpg",
    "guides": [
      "68e78398ada04e16be2e10b0",
      "68e78330afe6a66336d48bf1"
    ]
}

POST {{host}}/{{uri_prefix}}/tours/5c88fa8cf4afda39709c2970/reviews
Authorization: Bearer {{token}}
Content-Type: application/json
{
    "review": "Amazing tour 2!!",
    "rating": 3
}

POST {{host}}/{{uri_prefix}}/bookings/?tour=5c88fa8cf4afda39709c2970&user=5c8a1f292f8fb814b56fa184&price=2997
Authorization: Bearer {{token}}

GET {{host}}/{{uri_prefix}}/bookings/checkout-session/5c88fa8cf4afda39709c2970
Authorization: Bearer {{token}}
