@host = http://localhost:3000
@uri_prefix = api/v1

GET {{host}}/{{uri_prefix}}/tours?sort=-price&fields=name&page=1&limit=10

GET {{host}}/{{uri_prefix}}/tours

GET {{host}}/{{uri_prefix}}/tours/top-5-cheap

GET {{host}}/{{uri_prefix}}/tours/tour-stats

GET {{host}}/{{uri_prefix}}/tours/monthly-plan/2021

GET {{host}}/{{uri_prefix}}/tours/wwww

GET {{host}}/{{uri_prefix}}/users

GET {{host}}/{{uri_prefix}}/users/12

DELETE {{host}}/{{uri_prefix}}/tours/68e38a7b1f88a27c05aa54b3

POST {{host}}/{{uri_prefix}}/tours
Content-Type: application/json
{
    "name": "The Test",
    "duration": 5,
    "maxGroupSize": 25,
    "difficulty": "easy",
    "rating": 6,
    "price": 397,
    "priceDiscount": 300,
    "summary": "Breathtaking hike through the Canadian Banff National Park",
    "description": "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.\nLorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "imageCover": "tour-1-cover.jpg",
    "secretTour": true
}

PATCH {{host}}/{{uri_prefix}}/tours/68e38a7b1f88a27c05aa54b3
Content-Type: application/json
{
    "rating": 4.8,
    "price": 350
}

GET https://www.natours.dev/api/v1/tours

GET https://dog.ceo/api/breeds/image/random